[package]
name = "bevy-experiments"
version = "0.1.0"
edition = "2021"

[features]
trace = ["bevy/trace", "bevy/trace_tracy"]

[dependencies]
bevy = "~0.6"
bevy_egui = "~0.10"
bitflags = "~1.3"
itertools = "~0.10"
wgpu = "~0.12"
